version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-net

  customer-service:
    build: ./customer-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/customerDB
    depends_on:
      - mongodb
    networks:
      - ecommerce-net

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/productDB
    depends_on:
      - mongodb
    networks:
      - ecommerce-net

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/orderDB
      - CUSTOMER_SERVICE_URL=http://customer-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongodb
      - customer-service
      - product-service
      - payment-service
    networks:
      - ecommerce-net

  payment-service:
    build: ./payment-service
    ports:
      - "3004:3004"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-net

  transaction-worker:
    build: ./transaction-worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017/transactionDB
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge